version: '3'

services:
  products-db:
    container_name: auth_db
    image: postgres:16.3
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  cache:
    image: redis:7.2.5-alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
